name: Build HidGuardian

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Install WDK for Windows 7
        run: |
          Invoke-WebRequest -Uri https://go.microsoft.com/fwlink/?linkid=528353 -OutFile WDKSetup.exe
          Start-Process -FilePath .\WDKSetup.exe -ArgumentList "/quiet /norestart" -NoNewWindow -Wait

      - name: Build HidGuardian (x64)
        run: msbuild HidGuardian.sln /t:Build /p:Configuration=Release /p:Platform=x64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HidGuardian-Build
          path: |
            x64/Release/*.sys
            x64/Release/*.cat
            x64/Release/*.inf
